### ISSUE TITLE
"Grados" en lugar de "magnitud"

### ISSUE THREAD

**Issue by ppalaciosa** [aniversarioperu/salvitobot#24]
http://utero.pe/2015/10/04/temblor-de-5-4-grados-mwb-se-registro-a-33km-sso-de-lluta-peru/
De acuerdo a los estándares usuales, debe decirse "sismo de magnitud X" en lugar de "sismo de grado X"

Fuente:
http://ciencia.utero.pe/2015/10/02/desterrando-la-escala-de-richter/

**Comment by aniversarioperu** [comment]
gracias, voy a corregir! :smile_cat:
